spring.application.name=CLOUD-CONFIG-SERVER
server.port=8888

# Make the configuration server as service registry client
eureka.client.service-url.defaultZone=http://localhost:8083/eureka/

# Git repository configuration
spring.cloud.config.server.git.uri=https://github.com/sushil721/cloud-config-server-repository
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main