spring.application.name=API-GATEWAY-SERVICE
server.port=8080

#Spring Cloud Netflix Eureka Service Registry properties
eureka.client.service-url.defaultZone=http://localhost:8083/eureka/

## Enable auto registration in gateway with Eureka
## For this we need to add service name in url. Ex: http://localhost:8080/employee-service/api/employees/1
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.org.springframework.cloud.gateway=DEBUG

### Routes for Employee Service
#spring.cloud.gateway.routes[0].id=EMPLOYEE-SERVICE
#spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/employees/(?<segment>.*), /${segment}

### Routes for DEPARTMENT Service
#spring.cloud.gateway.routes[1].id=DEPARTMENT-SERVICE
#spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**


#swagger configuration
#springdoc.swagger-ui.path=/swagger-ui-employee.html
#springdoc.swagger-ui.operationsSorter=method

## Micrometer Configuration for Tracing
#management.tracing.sampling.probability=1.0
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.org.springframework.web=DEBUG
